<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_import"
 *
 * Auto generated by Extension Builder 2016-05-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'tollwerk Importer',
    'description' => 'General purpose mass importer module',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => 'fileadmin/user_upload/import',
    'clearCacheOnLoad' => 0,
    'version' => '',
    'constraints' => array(
        'depends' => array(
            'typo3' => '8.0.0-9.99.99',
            'extbase' => '1.0.0-0.0.0',
            'fluid' => '1.0.0-0.0.0',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);
